---
- ansible.builtin.import_playbook: update.yml

- name : Add Site
  gather_facts: false
  hosts: all
  vars:
    - aci_login: &mso_login
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: "{{ validate_certs }}"
  tasks:

    - name: Add a new DCNM site
      cisco.mso.mso_rest:
        <<: *mso_login
        path: "/api/config/v2/addsite/"
        method: post
        content:
          {
            "url": "{{ item.controller_url }}",
            "siteType": "ACI",
            "name": "{{ item.name }}",
            "aci": {
              "userName": "{{ item.controller_username }}",
              "password": "{{ item.controller_password }}",
              "inbandEpgDN": "",
              "loginDomain": ""
            },
            "latitude": "",
            "longitude": ""
          }
      delegate_to: localhost
      loop: "{{ site }}"
      when: site is defined
      loop_control:
        pause: 2


    - name: Configure site as Managed by MSO
      cisco.mso.mso_rest:
        <<: *mso_login
        path: "/mso/api/v2/sites/manage"
        method: post
        content:
          {
            "id": "",
            "common": {
              "name": "{{ item.name }}",
              "displayName": "{{ item.name }}",
              "urls": [
                  "{{ 'https://%s:443' % item.controller_url }}"
              ],
              "username": "{{ item.controller_username }}",
              "platformType": "Apic",
              "siteVersion": "{{ item.controller_password }}",
              "siteId": "{{ item.site_id | int }}"
            },
            "health": { },
            "apic": { },
            "dcnm": {}
          }
      delegate_to: localhost
      loop: "{{ site }}"
      when: site is defined