---
- ansible.builtin.import_playbook: update.yml
- name : Deploy
  gather_facts: false
  hosts: all
  vars:
    - aci_login: &mso_login
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: "{{ validate_certs }}"
  tasks:

    - name: Deploy a schema template
      cisco.mso.mso_schema_template_deploy:
        <<: *mso_login
        schema: "{{ item.schema_name }}"
        template: "{{ item.name }}"
        state: deploy
      delegate_to: localhost
      loop: "{{ template }}"
      when: template is defined





