---
- import_playbook: update.yml
- name : Fabric Template Policies
  gather_facts: false
  hosts: all
  tasks:

    - name: Fabric Policies Template
      cisco.mso.ndo_fabric_policies_template:
        template: "{{ item.name }}"
        state: "{{ item.status if item.status is defined and item.status != '' else omit }}"
      loop: "{{ fabric_policies_template }}"
      when: fabric_policies_template is defined

    - name: Add a site to Fabric Policies Template
      cisco.mso.ndo_fabric_policies_template_site:
        template: "{{ item.name }}"
        site: "{{ item.site }}"
        state: "{{ item.status if item.status is defined and item.status != '' else omit }}"
      loop: "{{ fabric_policies_template_site }}"
      when: fabric_policies_template_site is defined
