---
- import_playbook: update.yml
- name : Fabric Template Policies
  gather_facts: false
  hosts: all
  tasks:

    - name: Fabric Policies Template
      cisco.mso.ndo_fabric_policies_template:
        template: "{{ item.name }}"
        state: "{{ item.status if item.status is defined and item.status != '' else omit }}"
      loop: "{{ fabric_policies_template }}"
      when: fabric_policies_template is defined

    - name: Add a site to Fabric Policies Template
      cisco.mso.ndo_fabric_policies_template_site:
        template: "{{ item.name }}"
        site: "{{ item.site }}"
        state: "{{ item.status if item.status is defined and item.status != '' else omit }}"
      loop: "{{ fabric_policies_template_site }}"
      when: fabric_policies_template_site is defined

    - name: Add a new VLAN encap block
      cisco.mso.ndo_fabric_policies_vlan_pool_encap_block:
        pool: "{{ item.vlan_pool }}"
        block_start: "{{ item.start_vlan | int }}"
        block_end: "{{ item.stop_vlan | int }}"
        template: "{{ item.fabric_policies_template }}"
        state: "{{ item.status if item.status is defined and item.status != '' else omit }}"
      loop: "{{ vlan_encap_block }}"
      when: vlan_encap_block is defined

    - name: Add a new Domain
      cisco.mso.ndo_fabric_policies_domain:
        domain: "{{ item.name }}"
        domain_type: "{{ item.type }}"
        template: "{{ item.fabric_policies_template }}"
        pool: "{{ item.vlan_pool if item.vlan_pool is defined and item.vlan_pool != '' else omit }}"
        description: "{{ item.description if item.description is defined and item.description != '' else omit }}"
        state: "{{ item.status if item.status is defined and item.status != '' else omit }}"
      loop: "{{ domain }}"
      when: domain is defined


