---
#- import_playbook: update.yml
- name : Fabric Template Policies
  gather_facts: false
  hosts: all
  tasks:

    - name: Fabric Policies Template
      cisco.mso.ndo_fabric_policies_template:
        template: "{{ item.name }}"
        template_type: 'fabricResource'
        state: "{{ item.status if item.status is defined and item.status != '' else omit }}"
      loop: "{{ fabric_resources_template }}"
      when: fabric_resources_template is defined
      register: result
      retries: 3
      until: result is not failed

    - name: Add a site to Fabric Policies Template
      cisco.mso.ndo_fabric_policies_template_site:
        template: "{{ item.name }}"
        site: "{{ item.site }}"
        template_type: 'fabricResource'
        state: "{{ item.status if item.status is defined and item.status != '' else omit }}"
      loop: "{{ fabric_resources_template_site }}"
      when: fabric_resources_template_site is defined
      register: result
      retries: 3
      until: result is not failed

