---
- ansible.builtin.import_playbook: update.yml

- name : Tenants
  gather_facts: false
  hosts: all

  tasks:
    - name: Add Tenant
      cisco.mso.mso_tenant:
        tenant: "{{ item.name }}"
        description: "{{ item.description if item.status is defined else omit }}"
        state: "{{ item.status if item.status is defined else omit }}"
      loop: "{{ tenant }}"
      when: tenant is defined

    - name: Associate Tenant to Site
      cisco.mso.mso_tenant:
        tenant: "{{ item.tenant }}"
        state: "{{ item.status if item.status is defined else omit }}"
        sites: "{{ item.site }}"
      loop: "{{ tenant_site_association }}"
      when: tenant_site_association is defined


