---
- ansible.builtin.import_playbook: update.yml
- name : Schemas and Templates
  gather_facts: false
  hosts: all
  tasks:

    - name: Add a new template to a schema
      cisco.mso.mso_schema_template:
        schema: "{{ item.schema }}"
        state: "{{ item.status if item.status is defined else omit }}"
        template: "{{ item.name }}"
        tenant: "{{ item.tenant }}"
        template_type: "{{ item.template_type }}"
        schema_description: "{{ item.schema_description if item.schema_description is defined else omit }}"
        template_description: "{{ item.description if item.description is defined else omit }}"
      loop: "{{ template }}"
      when: template is defined and item.schema is defined and item.schema != ''

    - name: Add a site to a schema
      cisco.mso.mso_schema_site:
        schema: "{{ item.schema }}"
        template: "{{ item.template }}"
        site: "{{ item.site }}"
        state: "{{ item.status if item.status is defined else omit }}"
      loop: "{{ template_site_association }}"
      when: template_site_association is defined and item.schema is defined and item.schema != ''