---
- ansible.builtin.import_playbook: update.yml

- name : Bridge Domains
  gather_facts: false
  hosts: all
  tasks:

    - name: Add a new BD
      cisco.mso.mso_schema_template_bd:
        schema: "{{ item.schema_name }}"
        template: "{{ item.template_name }}"
        layer2_stretch: "{{ item.l2stretch }}"
        intersite_bum_traffic: "{{ item.intersiteBumTrafficAllow if item.intersiteBumTrafficAllow is defined and item.intersiteBumTrafficAllow != '' else omit }}"
        layer2_unknown_unicast: "{{ item.l2_unknown_unicast  if item.l2_unknown_unicast is defined and item.l2_unknown_unicast != '' else omit }}"
        vrf:
          name : "{{ item.vrf_name  }}"
          schema: "{{ item.vrf_schema_name }}"
          template: "{{ item.vrf_template_name }}"
        state: "{{ item.status if item.status is defined else omit }}"
        bd : "{{ item.name }}"
        arp_flooding: "{{ item.arp_flooding if item.arp_flooding is defined and item.arp_flooding != '' else omit }}"
        unicast_routing: "{{ item.unicast_routing if item.unicast_routing is defined and item.unicast_routing != '' else omit }}"
      loop: "{{ bridge_domain  }}"
      when: bridge_domain is defined


    - name: Add a new subnet to a Stretched BD
      cisco.mso.mso_schema_template_bd_subnet:
        schema: "{{ item.schema_name }}"
        template: "{{ item.template_name }}"
        bd: "{{ item.bd_name }}"
        description: "{{ item.description if item.status is defined else omit }}"
        subnet: "{{ item.gateway_ip }}"
        scope: "{{ item.subnet_scope }}"
        shared: "{{ item.shared if item.shared is defined and item.shared != '' else omit }}"
        state: "{{ item.status if item.status is defined else omit }}"
      loop: "{{ bridge_domain_subnet }}"
      when: bridge_domain_subnet is defined and item.site_name == ''

    - name: Add Non Streched BD to the Site
      cisco.mso.mso_schema_site_bd:
        site: "{{ item.site_name }}"
        schema: "{{ item.schema_name }}"
        template: "{{ item.template_name }}"
        bd: "{{ item.bd_name }}"
        state: "{{ item.status if item.status is defined else omit }}"
      loop: "{{ bridge_domain_subnet  }}"
      when: bridge_domain_subnet is defined and item.site_name != ''

    - name: Add a new subnet to a Non Stretched BD
      cisco.mso.mso_schema_site_bd_subnet:
        schema: "{{ item.schema_name }}"
        template: "{{ item.template_name }}"
        description: "{{ item.description if item.status is defined else omit }}"
        bd: "{{ item.bd_name }}"
        subnet: "{{ item.gateway_ip }}"
        scope: "{{ item.subnet_scope }}"
        shared: "{{ item.shared if item.shared is defined and item.shared != '' else omit }}"
        state: "{{ item.status if item.status is defined else omit }}"
        site: "{{ item.site_name }}"
      loop: "{{ bridge_domain_subnet }}"
      when: bridge_domain_subnet is defined and item.site_name != ''
