---
- ansible.builtin.import_playbook: update.yml
- name : Application Network Profiles
  gather_facts: false
  hosts: all
  tasks:
  
    - name: Add a new ANP
      cisco.mso.mso_schema_template_anp:
        schema: "{{ item.schema_name }}"
        template: "{{ item.template_name }}"
        anp : "{{ item.name }}"
        state: "{{ item.status if item.status is defined else omit }}"
      loop: "{{ application_profile }}"
      when: application_profile is defined
