---
- ansible.builtin.import_playbook: update.yml
- name : Application Network Profiles
  gather_facts: false
  hosts: all
  vars:
    - aci_login: &mso_login
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: "{{ validate_certs }}"
  tasks:
  
    - name: Add a new ANP
      cisco.mso.mso_schema_template_anp:
        <<: *mso_login
        schema: "{{ item.schema_name }}"
        template: "{{ item.template_name }}"
        anp : "{{ item.name }}"
        state: "{{ item.status if item.status is defined else omit }}"
      delegate_to: localhost
      loop: "{{ application_profile }}"
      when: application_profile is defined
