---
- ansible.builtin.import_playbook: update.yml
- name : Application Network Profiles
  gather_facts: false
  hosts: all
  tasks:
  
    - name: Add a new ANP
      cisco.mso.mso_schema_template_anp:
        schema: "{{ item.schema }}"
        template: "{{ item.template }}"
        anp : "{{ item.name }}"
        description: "{{ item.description if item.description is defined and item.description != '' else omit }}"
        state: "{{ item.status if item.status is defined and item.status != '' else omit }}"
      loop: "{{ application_profile }}"
      when: application_profile is defined
