---
- import_playbook: update.yml
- name : Contracts
  gather_facts: false
  hosts: all
  vars:
    - aci_login: &mso_login
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: "{{ validate_certs }}"
  tasks:

    - name: Enable vzAny attribute on VRF
      cisco.mso.mso_schema_template_vrf:
        <<: *mso_login
        schema: "{{ item.vrf_schema_name }}"
        template: "{{ item.vrf_template_name }}"
        vrf: "{{ item.vrf }}"
        vzany: 'yes'
      delegate_to: localhost
      loop: "{{ vrf_contract }}"
      when: vrf_contract is defined


    - name: Add a contract to a VRF
      cisco.mso.mso_schema_template_vrf_contract:
        <<: *mso_login
        schema: "{{ item.vrf_schema_name }}"
        template: "{{ item.vrf_template_name }}"
        state: "{{ item.status if item.status is defined else omit }}"
        vrf: "{{ item.vrf }}"
        contract:
          name: "{{ item.contract_name }}"
          type: "{{ item.contract_relationship }}"
          schema: "{{ item.contract_schema_name }}"
          template: "{{ item.contract_template_name }}"
      delegate_to: localhost
      loop: "{{ vrf_contract }}"
      when: vrf_contract is defined