---
- ansible.builtin.import_playbook: update.yml
- name : Deploy
  gather_facts: false
  hosts: all
  tasks:

    - name: Deploy a schema template
      cisco.mso.ndo_schema_template_deploy:
        schema: "{{ item.schema }}"
        template: "{{ item.name }}"
        state: deploy
      loop: "{{ template }}"
      when: template is defined





