---
- name : Update host vars
  gather_facts: false
  hosts: localhost

  tasks:

    - name: Update host vars
      ansible.builtin.shell: python3 "{{ playbook_dir }}"/../scripts/excel_to_yaml.py
      delegate_to: localhost
      when: diff_mode_enabled == false

    - name: Update host vars - Diff mode
      ansible.builtin.shell: python3 "{{ playbook_dir }}"/../scripts/excel_to_yaml.py --mode diff_mode
      delegate_to: localhost
      when: diff_mode_enabled == true

    - meta: refresh_inventory